title: DevOps practices for developer productivity
description: This lab walks you through setting up the development environment, deploying your appication, and implementing load testing and secure practices.
theme: just-the-docs

# url: https://solid-couscous-mz1ger5.pages.github.io/

aux_links:
  "Implementing DevOps practices to accelerate developer productivity": 
    - "https://github.com/microsoft/TechExcel-Implementing-DevOps-practices-to-accelerate-developer-productivity"


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
